- binary_sensor:
    # These sensors rely on ha-illuminance custom component that combines elevation data with weather data,
    # such that dark rainy/cloudy conditions may turn on lights.

    - name: Sufficiently Dark For Indoor Lights
      icon: mdi:moon-waning-crescent
      state: >
        {{ states('sensor.illuminance') | int(0) < 4000 }}

    - name: Sufficiently Dark For Outdoor Lights
      icon: mdi:moon-waning-crescent
      state: >
        {{ states('sensor.illuminance') | int(0) < 500 }}
