- alias: Test garden fence vibation
  id: test-garden-fence-vibration
  trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/Vibration Garden Fence/action"
  action:
    - service: notify.mobile_app_J16
      data:
        title: Graden fence action
        message: >
          Action: {{ trigger.payload }}
  mode: restart
