# https://community.home-assistant.io/t/zigbee2mqtt-enocean-ptm-215z-friends-of-hue-switch/429770
- alias: Switch Hall 0
  id: switch_hall_0
  description: Switch Hall 0 to control lights
  use_blueprint:
    path: custom/friends_of_hue_switch.yaml
    input:
      controller: Switch Hall 0
      button_1_released:
        - action: switch.turn_on
          target:
            entity_id:
              - switch.adaptive_lighting_adapt_brightness_hall_0_spot
              - switch.adaptive_lighting_adapt_brightness_hall_0_wall
        - action: light.turn_on
          target:
            entity_id: &ref_hall_0
              - light.light_group_hall_0_spot
              - light.light_hall_0_wall
      button_2_released:
        - action: light.turn_off
          target:
            entity_id: *ref_hall_0
      button_4_released:
        - action: input_boolean.toggle
          target:
            entity_id: input_boolean.sleep_mode
