- platform: template
  sensors:
    weather_cloud_coverage:
       unique_id: 'weather_cloud_coverage'
       friendly_name: Weather Cloud Coverage
       value_template: >-
        {{ state_attr("weather.forecast_home", "cloud_coverage") | round(0) }}
