# N.b.: when adding/removing configs, also update:
# - automation/light_adaptive.yaml
# - automation/sleep_mode.yaml

- name: "hall-0-spot"
  lights: ["light.light_group_hall_0_spot"]
  min_brightness: 15
  max_brightness: 20
  min_color_temp: 2500
  max_color_temp: 4000

- name: "hall-0-wall"
  lights: ["light.light_hall_0_wall"]
  min_brightness: 10
  max_brightness: 15

- name: "toilet"
  lights: ["light.light_toilet"]
  min_brightness: 50
  max_brightness: 60
  min_color_temp: 2500
  max_color_temp: 4000

- name: "living-spot-always"
  lights: ["light.light_group_living_spot_always"]
  min_brightness: 35
  max_brightness: 40
  min_color_temp: 2500
  max_color_temp: 4000

- name: "living-spot-dark-outside"
  lights: ["light.light_group_living_spot_dark_outside"]
  min_brightness: 35
  max_brightness: 40
  min_color_temp: 2500
  max_color_temp: 4000

- name: "living-white-cabinet"
  lights: ["light.light_living_white_cabinet"]
  min_brightness: 5
  max_brightness: 15
  # Is more yellow than the spots, so make it go to warmer color temp:
  min_color_temp: 2000
  max_color_temp: 4000

- name: "stair-cabinet"
  lights: ["light.light_stair_cabinet"]
  min_brightness: 30
  max_brightness: 70
  sleep_brightness: 20
  min_color_temp: 3000
  max_color_temp: 4000
  # It's nice to see it come on gradually, otherwise the effect finishes before the door is open:
  initial_transition: 2

- name: "dining-table"
  lights: ["light.light_dining_table"]
  min_brightness: 80
  max_brightness: 100
  sleep_brightness: 10
  min_color_temp: 2500
  max_color_temp: 4000

- name: "kitchen-middle"
  lights: ["light.light_group_kitchen_middle"]
  min_brightness: 25
  max_brightness: 30
  min_color_temp: 2700
  max_color_temp: 4000
  sleep_brightness: 5

- name: "kitchen-countertop"
  lights: ["light.light_group_kitchen_countertop"]
  min_brightness: 55
  max_brightness: 60
  min_color_temp: 2700
  max_color_temp: 4000
  sleep_brightness: 10

- name: "bathroom"
  lights: ["light.light_bathroom"]
  min_brightness: 20
  max_brightness: 30
  # The default of 1 is very low here and it kind of struggles to come on, do a bit higher:
  sleep_brightness: 3

- name: "bedroom-duco-ambiance"
  lights: ["light.light_group_bedroom_duco_ambiance"]
  min_brightness: 20
  max_brightness: 30
  min_color_temp: 2200
  max_color_temp: 4000
  max_sunset_time: "19:00:00"

- name: "bedroom-duco-color"
  lights: ["light.light_group_bedroom_duco_color"]
  min_brightness: 20
  max_brightness: 30
  min_color_temp: 2200
  max_color_temp: 4000
  max_sunset_time: "19:00:00"

- name: "bedroom-olivier-ambiance"
  lights: ["light.light_group_bedroom_olivier_ambiance"]
  min_brightness: 20
  max_brightness: 30
  min_color_temp: 2200
  max_color_temp: 4000
  max_sunset_time: "19:00:00"

- name: "bedroom-olivier-color"
  lights: ["light.light_group_bedroom_olivier_color"]
  min_brightness: 20
  max_brightness: 30
  min_color_temp: 2200
  max_color_temp: 4000
  max_sunset_time: "19:00:00"
