
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

recorder:
  purge_keep_days: 30  # default is 10 days

# Dirs to include
automation: !include_dir_merge_list automation/
sensor: !include_dir_merge_list sensor/
template: !include_dir_merge_list template/

# Files to include
group: !include groups.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_text: !include input_text.yaml
lovelace: !include lovelace.yaml
logbook: !include logbook.yaml
script: !include script.yaml
timer: !include timer.yaml

# Custom component config files to include
adaptive_lighting: !include adaptive_lighting.yaml
illuminance: !include illuminance.yaml
