illuminance_threshold_indoor_lights:
  # "Dark Outside" lights turn on when illuminance is below this threshold.
  name: Illuminance Threshold Indoor Lights
  initial: 2600
  min: 1000
  max: 6000
  step: 100
  unit_of_measurement: "lx"

illuminance_threshold_outdoor_lights:
  name: Illuminance Threshold Outdoor Lights
  initial: 300
  min: 100
  max: 1000
  step: 50
  unit_of_measurement: "lx"

wake_up_light_kids_minutes_until_green:
  name: Wake Up Light Kids Minutes Until Green
  initial: 15
  min: 1
  max: 30
  step: 1
  unit_of_measurement: "minutes"
  icon: "mdi:clock-plus-outline"
