adaptive_lighting:
  name: Adaptive Lighting
  icon: mdi:theme-light-dark

sleep_mode:
  name: Sleep Mode
  icon: mdi:sleep
sleep_mode_kids:
  name: Sleep Mode Kids
  icon: mdi:sleep

disco_olivier:
  name: Disco Olivier
  icon: mdi:party-popper
  initial: false
disco_duco:
  name: Disco Duco
  icon: mdi:party-popper
  initial: false

wake_up_light_kids_enabled:
  name: Wake Up Light Kids Enabled
  icon: mdi:alarm-check
  initial: true

wake_up_lights_kids_cycle_in_progress:
  name: Wake Up Lights Kids Cycle In Progress
  icon: mdi:alarm-check
  initial: false

# Not yet installed, coming soon:
# motion_activated_lights:
#   name: Motion Activated Lights
#   icon: mdi:motion-sensor

# TODO:
# housekeeping_mode:
#   # Toggle Adaptive Lighting + all motion sensors and set lights to max white.
#   name: Housekeeping Mode
#   icon: mdi:broom
