# TODO: apparently script blueprints are a thing, move tot that.

turn_on_light_kitchen_middle_dimmed:
  alias: "Turn on light kitchen middle dimmed"
  sequence:
    # Need to ensure that these values are below the minimum brightness configured in adaptive lighting.
    - service: "light.turn_on"
      data:
        brightness: 80
        transition: 5
      target:
        entity_id: light.light_group_kitchen_middle

turn_on_light_kitchen_countertop_dimmed:
  alias: "Turn on light kitchen countertop dimmed"
  sequence:
    # Need to ensure that these values are below the minimum brightness configured in adaptive lighting.
    - service: "light.turn_on"
      data:
        brightness: 160
        transition: 5
      target:
        entity_id: light.light_group_kitchen_countertop

turn_on_light_hall_0_spot_dimmed:
  alias: "Turn on light hall 0 spot dimmed"
  sequence:
    # Need to ensure that these values are below the minimum brightness configured in adaptive lighting.
    - service: "light.turn_on"
      data:
        brightness: 45
        transition: 5
      target:
        entity_id: light.light_group_hall_0_spot

turn_on_light_hall_0_wall_dimmed:
  alias: "Turn on light hall 0 wall dimmed"
  sequence:
    # Need to ensure that these values are below the minimum brightness configured in adaptive lighting.
    - service: "light.turn_on"
      data:
        brightness: 35
        transition: 5
      target:
        entity_id: light.light_hall_0_wall

wake_up_light_kids_set_green:
  alias: "Wake up light kids: Set to green"
  sequence:
    - service: adaptive_lighting.set_manual_control
      entity_id:
        - switch.adaptive_lighting_bedroom_duco_color
        - switch.adaptive_lighting_bedroom_olivier_color
    - service: light.turn_on
      target:
        entity_id:
          - light.light_group_bedroom_duco_color
          - light.light_group_bedroom_olivier_color
      data:
        color_name: "green"
        brightness_pct: 10
        transition: 1
