# TODO: apparently script blueprints are a thing, move tot that.

turn_on_light_kitchen_middle_dimmed:
  alias: "Turn on light kitchen middle dimmed"
  sequence:
    # Need to ensure that these values are below the minimum brightness configured in adaptive lighting.
    - service: "light.turn_on"
      data:
        brightness: 48
        transition: 5
      target:
        entity_id: light.light_group_kitchen_middle

turn_on_light_kitchen_countertop_dimmed:
  alias: "Turn on light kitchen countertop dimmed"
  sequence:
    # Need to ensure that these values are below the minimum brightness configured in adaptive lighting.
    - service: "light.turn_on"
      data:
        brightness: 96
        transition: 5
      target:
        entity_id: light.light_group_kitchen_countertop

turn_on_light_bathroom_dimmed:
  alias: "Turn on light bathroom dimmed"
  sequence:
    # Adaptive lighting overrides the brightness and transition below.
    # Reason unknown. Workaround: mark manual first.
    - action: adaptive_lighting.set_manual_control
      entity_id: switch.adaptive_lighting_bathroom
    # Need to ensure that these values are below the minimum brightness configured in adaptive lighting.
    - service: "light.turn_on"
      data:
        brightness: 10
        transition: 5
      target:
        entity_id: light.light_bathroom

turn_on_light_hall_0_spot_dimmed:
  alias: "Turn on light hall 0 spot dimmed"
  sequence:
    # Need to ensure that these values are below the minimum brightness configured in adaptive lighting.
    - service: "light.turn_on"
      data:
        brightness: 35
        transition: 5
      target:
        entity_id: light.light_group_hall_0_spot

turn_on_light_hall_0_wall_dimmed:
  alias: "Turn on light hall 0 wall dimmed"
  sequence:
    # Need to ensure that these values are below the minimum brightness configured in adaptive lighting.
    - service: "light.turn_on"
      data:
        brightness: 28
        transition: 5
      target:
        entity_id: light.light_hall_0_wall
